### PR TITLE
Contributors

### PR DESCRIPTION
**Pull request by TheGrinch00**
I don't know why but in my repo there are other people registered as contributors (?)

### CODE REVIEW

**Review by Thanzex — CHANGES_REQUESTED** [review]
It usually updates within 24 hours and the result is cached.
Something seems a little off though, as you can see in the repo [contributors page](https://github.com/JEToP/jetop_credentials_frontend/graphs/contributors?) only @powext  appears, maybe contributors-img is based on that. 
We should understand why this is happening, as in the [backend repo](https://github.com/JEToP/jetop_credentials_backend/graphs/contributors) everything is normal.
I wouldn't change the repo as it wouldn't really solve the problem

**Comment by powext** [comment]
> We should understand why this is happening, as in the backend repo everything is normal.

I think because the website takes the contributors from the main branch

**Comment by TheGrinch00** [comment]
So, maybe if you make a merge from develop to master, it will update

**Comment by powext** [comment]
Yeah I'm gonna merge it once we have a stable release

**Pull request closed without merging**
